### ISSUE TITLE
AddMetadataByUrl ??

### ISSUE THREAD

**Issue by svrooij** [elerch/SAML2#2]
It would be nice to have an AddMetadataByUrl method in SAML2.Config.IdentityProviders because the identity provider we use only lets us use their metadata for 1 day. So at this moment I should create a Deamon that downloads the metadata every day. Put it in the correct directory and hope it goes well.

Is this easy to implement?

Thanks for the help and for this great library.

**Comment by elerch** [comment]
I just pushed some code in a58548bb84769ff1687e14824182d79544e579c0 to do this. Unfortunately it was a little trickier due to the way the original project was structured, but it wasn't too bad and the metadata tests are still passing. 

I added a commented AddByMetadataUrl with your metadata endpoint into the sample project's startup class so you can see how it would be used. It's working for me, but before I publish to Nuget would you give it a run through?

**Comment by svrooij** [comment]
Thanks for the quick fix, will try this on thursday.

Where should I begin, if I open the solution in VS2013 it doesn't build. Something about metadata and a custom tool

**Comment by emw-ghertner** [comment]
Hi Emil,

Thank you very much for your work on this.

I cannot get this project to build either.  I would really like to use the AddByMetadataUrl feature.

I get the following errors
`CSC : error CS2001: Source file 'ErrorMessages.Designer.cs' could not be found`
`CSC : error CS2001: Source file 'TraceMessages.Designer.cs' could not be found`

Any help would be appreciated.

Eric

**Comment by emw-ghertner** [comment]
Disregard I figured out how to get Visual Studio 2013 to regenerate the Designers.
